#!/bin/bash
################################################################################
# FRR Functions Library
#
# Core functions for generating and deploying FRR configurations.
# Can be used standalone or integrated with VDC deployment.
#
# Usage:
#   source frr-functions.sh
#   generate_frr_config "device_name" "router_id" "asn" "neighbors_array"
################################################################################

# Determine script directory for relative paths
FRR_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRR_PROJECT_ROOT="$(dirname "$FRR_SCRIPT_DIR")"

# Colors for output (only define if not already defined)
if [[ -z "${RED:-}" ]]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BLUE='\033[0;34m'
    NC='\033[0m'
fi

# Logging functions (only define if not already defined)
if ! type frr_log_info &>/dev/null; then
    frr_log_info() {
        echo -e "${BLUE}[FRR]${NC} $*"
    }

    frr_log_success() {
        echo -e "${GREEN}[FRR]${NC} $*"
    }

    frr_log_warn() {
        echo -e "${YELLOW}[FRR]${NC} $*"
    }

    frr_log_error() {
        echo -e "${RED}[FRR]${NC} $*"
    }
fi

################################################################################
# Configuration Generation Functions
################################################################################

# Generate FRR daemons configuration
# Usage: generate_frr_daemons_config
# Output: Writes daemons config to stdout
generate_frr_daemons_config() {
    cat <<'EOF'
zebra=yes
bgpd=yes
ospfd=no
ospf6d=no
ripd=no
ripngd=no
isisd=no
pimd=no
ldpd=no
nhrpd=no
eigrpd=no
babeld=no
sharpd=no
pbrd=no
bfdd=no
fabricd=no
vrrpd=no

vtysh_enable=yes
zebra_options="  -A 127.0.0.1 -s 90000000"
bgpd_options="   -A 127.0.0.1"
EOF
}

# Generate complete FRR configuration
# Usage: generate_frr_config <device_name> <router_id> <asn> <neighbors> [options]
# Parameters:
#   device_name  - Hostname for the device
#   router_id    - BGP router ID (e.g., 10.1.0.1)
#   asn          - BGP AS number
#   neighbors    - Space-separated list of neighbor interfaces (e.g., "enp2s0 enp3s0")
#   options      - Optional JSON object with additional settings
# Output: Writes FRR config to stdout
#
# Environment variables (can be used instead of options):
#   FRR_VERSION              - FRR version string (default: 10.0)
#   FRR_PEER_GROUP           - BGP peer group name (default: FABRIC)
#   FRR_REDISTRIBUTE         - Redistribution type (default: connected)
#   FRR_REDISTRIBUTE_ROUTE_MAP - Route-map for redistribution (default: none)
#   FRR_REDISTRIBUTE_INTERFACES - Space-separated list of interfaces to match in route-map
#                                 (default: "lo1 dum-ex" for hypervisors, empty for switches)
generate_frr_config() {
    local device_name="$1"
    local router_id="$2"
    local asn="$3"
    local neighbors="$4"
    local options="${5:-}"

    # Parse options (defaults)
    local frr_version="${FRR_VERSION:-10.0}"
    local peer_group="${FRR_PEER_GROUP:-FABRIC}"
    local redistribute_type="${FRR_REDISTRIBUTE:-connected}"
    local redistribute_route_map="${FRR_REDISTRIBUTE_ROUTE_MAP:-}"
    local redistribute_interfaces="${FRR_REDISTRIBUTE_INTERFACES:-}"

    # Parse options JSON if provided
    if [[ -n "$options" ]]; then
        frr_version=$(echo "$options" | yq eval '.frr_version // "10.0"' - 2>/dev/null || echo "10.0")
        peer_group=$(echo "$options" | yq eval '.peer_group // "FABRIC"' - 2>/dev/null || echo "FABRIC")
        redistribute_type=$(echo "$options" | yq eval '.redistribute_type // "connected"' - 2>/dev/null || echo "connected")
        redistribute_route_map=$(echo "$options" | yq eval '.redistribute_route_map // ""' - 2>/dev/null || echo "")
        # redistribute_interfaces can be a YAML array or space-separated string
        local ri_raw=$(echo "$options" | yq eval '.redistribute_interfaces // ""' - 2>/dev/null || echo "")
        if [[ -n "$ri_raw" && "$ri_raw" != "null" ]]; then
            # Check if it's an array (starts with -)
            if echo "$ri_raw" | grep -q "^-"; then
                redistribute_interfaces=$(echo "$options" | yq eval '.redistribute_interfaces | join(" ")' - 2>/dev/null || echo "")
            else
                redistribute_interfaces="$ri_raw"
            fi
        fi
    fi

    # Start generating config
    cat <<EOF
!
! FRRouting configuration for $device_name
! Generated by FRR Configuration Module
!
frr version $frr_version
frr defaults traditional
hostname $device_name
log syslog informational
service integrated-vtysh-config
!
! Configure lo1 with router ID (managed by FRR, applied on restart/reboot)
interface lo1
 ip address $router_id/32
 description BGP Router ID
!
! BGP Configuration with Unnumbered Support
router bgp $asn
 bgp router-id $router_id
 bgp log-neighbor-changes
 bgp bestpath as-path multipath-relax
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 !
 ! Fabric peer-group for unnumbered BGP
 neighbor $peer_group peer-group
 neighbor $peer_group remote-as external
 neighbor $peer_group capability extended-nexthop
 !
EOF

    # Add BGP neighbors
    for neighbor in $neighbors; do
        cat <<EOF
 ! BGP neighbor on $neighbor
 neighbor $neighbor interface peer-group $peer_group
 !
EOF
    done

    # Address family configuration
    cat <<EOF
 address-family ipv4 unicast
  neighbor $peer_group activate
  neighbor $peer_group route-map ALLOW-ALL in
  neighbor $peer_group route-map ALLOW-ALL out
EOF

    # Add redistribution
    if [[ -n "$redistribute_route_map" ]]; then
        cat <<EOF
  redistribute $redistribute_type route-map $redistribute_route_map
EOF
    else
        cat <<EOF
  redistribute $redistribute_type
EOF
    fi

    cat <<EOF
  maximum-paths 64
  maximum-paths ibgp 64
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor $peer_group activate
 exit-address-family
!
! Route maps
! Allow all routes from BGP neighbors
route-map ALLOW-ALL permit 10
 set src $router_id
!
ip protocol bgp route-map ALLOW-ALL
EOF

    # Add redistribute route-map if specified
    if [[ -n "$redistribute_route_map" && "$redistribute_route_map" != "ALLOW-ALL" ]]; then
        if [[ -n "$redistribute_interfaces" ]]; then
            cat <<EOF
! Redistribute only connected routes from specified interfaces
! Each interface needs a separate route-map permit entry
EOF
            # Create separate permit entry for each interface
            local seq=10
            for iface in $redistribute_interfaces; do
                cat <<EOF
route-map $redistribute_route_map permit $seq
 match interface $iface
!
EOF
                seq=$((seq + 10))
            done
        else
            cat <<EOF
route-map $redistribute_route_map permit 10
!
EOF
        fi
    fi

    cat <<EOF
line vty
!
end
EOF
}

# Generate FRR config specifically for hypervisors (redistributes only specified interfaces)
# Usage: generate_frr_hypervisor_config <device_name> <router_id> <asn> <neighbors> [redistribute_interfaces]
# Parameters:
#   redistribute_interfaces - Optional: space-separated list of interfaces to redistribute
#                             (default: "lo1 dum-ex")
generate_frr_hypervisor_config() {
    local device_name="$1"
    local router_id="$2"
    local asn="$3"
    local neighbors="$4"
    local redistribute_interfaces="${5:-lo1 dum-ex}"

    FRR_REDISTRIBUTE_ROUTE_MAP="REDISTRIBUTE-CONNECTED" \
    FRR_REDISTRIBUTE_INTERFACES="$redistribute_interfaces" \
    generate_frr_config "$device_name" "$router_id" "$asn" "$neighbors"
}

# Generate FRR config specifically for switches (redistributes all connected)
# Usage: generate_frr_switch_config <device_name> <router_id> <asn> <neighbors>
generate_frr_switch_config() {
    local device_name="$1"
    local router_id="$2"
    local asn="$3"
    local neighbors="$4"

    FRR_REDISTRIBUTE_ROUTE_MAP="" \
    generate_frr_config "$device_name" "$router_id" "$asn" "$neighbors"
}

################################################################################
# Neighbor Discovery Functions
################################################################################

# Get neighbors from explicit config YAML
# Usage: get_neighbors_from_config <config_file> <device_index>
# Output: Space-separated list of neighbor interfaces
get_neighbors_from_config() {
    local config_file="$1"
    local device_index="$2"

    local neighbor_count=$(yq eval ".frr_config.devices[$device_index].neighbors | length" "$config_file" 2>/dev/null || echo "0")
    local neighbors=""

    for i in $(seq 0 $((neighbor_count - 1))); do
        local iface=$(yq eval ".frr_config.devices[$device_index].neighbors[$i].interface" "$config_file")
        if [[ -n "$iface" && "$iface" != "null" ]]; then
            neighbors="$neighbors $iface"
        fi
    done

    echo "$neighbors" | xargs  # Trim whitespace
}

# Get neighbors from VDC cabling configuration
# Usage: get_neighbors_from_vdc_cabling <vdc_config_file> <device_name>
# Output: Space-separated list of neighbor interfaces
get_neighbors_from_vdc_cabling() {
    local vdc_config="$1"
    local device_name="$2"

    local cable_count=$(yq eval '.cabling | length' "$vdc_config" 2>/dev/null || echo "0")
    local neighbors=""

    for i in $(seq 0 $((cable_count - 1))); do
        local src_device=$(yq eval ".cabling[$i].source.device" "$vdc_config")
        local src_iface=$(yq eval ".cabling[$i].source.interface" "$vdc_config")
        local dst_device=$(yq eval ".cabling[$i].destination.device" "$vdc_config")
        local dst_iface=$(yq eval ".cabling[$i].destination.interface" "$vdc_config")

        # Check if this device is involved in this cable
        if [[ "$src_device" == "$device_name" ]]; then
            neighbors="$neighbors $src_iface"
        elif [[ "$dst_device" == "$device_name" ]]; then
            neighbors="$neighbors $dst_iface"
        fi
    done

    echo "$neighbors" | xargs  # Trim whitespace
}

# Get device info from VDC topology
# Usage: get_vdc_device_info <vdc_config_file> <device_name>
# Output: JSON object with device info
get_vdc_device_info() {
    local vdc_config="$1"
    local device_name="$2"

    # Check hypervisors
    local hv_count=$(yq eval '.hypervisors | length' "$vdc_config" 2>/dev/null || echo "0")
    for i in $(seq 0 $((hv_count - 1))); do
        local name=$(yq eval ".hypervisors[$i].name" "$vdc_config")
        if [[ "$name" == "$device_name" ]]; then
            yq eval ".hypervisors[$i] | .type = \"hypervisor\"" "$vdc_config"
            return 0
        fi
    done

    # Check leaf switches
    local leaf_count=$(yq eval '.switches.leaf | length' "$vdc_config" 2>/dev/null || echo "0")
    for i in $(seq 0 $((leaf_count - 1))); do
        local name=$(yq eval ".switches.leaf[$i].name" "$vdc_config")
        if [[ "$name" == "$device_name" ]]; then
            yq eval ".switches.leaf[$i] | .type = \"switch\"" "$vdc_config"
            return 0
        fi
    done

    # Check spine switches
    local spine_count=$(yq eval '.switches.spine | length' "$vdc_config" 2>/dev/null || echo "0")
    for i in $(seq 0 $((spine_count - 1))); do
        local name=$(yq eval ".switches.spine[$i].name" "$vdc_config")
        if [[ "$name" == "$device_name" ]]; then
            yq eval ".switches.spine[$i] | .type = \"switch\"" "$vdc_config"
            return 0
        fi
    done

    # Check superspine switches
    local superspine_count=$(yq eval '.switches.superspine | length' "$vdc_config" 2>/dev/null || echo "0")
    for i in $(seq 0 $((superspine_count - 1))); do
        local name=$(yq eval ".switches.superspine[$i].name" "$vdc_config")
        if [[ "$name" == "$device_name" ]]; then
            yq eval ".switches.superspine[$i] | .type = \"switch\"" "$vdc_config"
            return 0
        fi
    done

    return 1
}

# List all devices from VDC topology
# Usage: list_vdc_devices <vdc_config_file>
# Output: One device name per line
list_vdc_devices() {
    local vdc_config="$1"

    # List hypervisors
    yq eval '.hypervisors[].name' "$vdc_config" 2>/dev/null || true

    # List leaf switches
    yq eval '.switches.leaf[].name' "$vdc_config" 2>/dev/null || true

    # List spine switches
    yq eval '.switches.spine[].name' "$vdc_config" 2>/dev/null || true

    # List superspine switches
    yq eval '.switches.superspine[].name' "$vdc_config" 2>/dev/null || true
}

################################################################################
# SSH Operations
################################################################################

# Wait for SSH to become available
# Usage: wait_for_ssh <host> <ssh_key_or_password> <auth_type> [max_attempts] [user]
# Returns: 0 if successful, 1 if timeout
wait_for_ssh() {
    local host="$1"
    local auth_credential="$2"
    local auth_type="${3:-key}"  # "key" or "password"
    local max_attempts="${4:-30}"
    local user="${5:-ubuntu}"
    local attempt=0

    frr_log_info "Waiting for SSH on $host..."

    while [[ $attempt -lt $max_attempts ]]; do
        if [[ "$auth_type" == "key" ]]; then
            if ssh -i "$auth_credential" \
                   -o StrictHostKeyChecking=no \
                   -o UserKnownHostsFile=/dev/null \
                   -o ConnectTimeout=5 \
                   -o BatchMode=yes \
                   "${user}@${host}" "echo ready" &>/dev/null; then
                frr_log_success "SSH available on $host"
                return 0
            fi
        else
            if sshpass -p "$auth_credential" ssh \
                   -o StrictHostKeyChecking=no \
                   -o UserKnownHostsFile=/dev/null \
                   -o ConnectTimeout=5 \
                   "${user}@${host}" "echo ready" &>/dev/null; then
                frr_log_success "SSH available on $host"
                return 0
            fi
        fi

        attempt=$((attempt + 1))
        sleep 10
    done

    frr_log_error "SSH timeout on $host after $max_attempts attempts"
    return 1
}

# Deploy FRR configuration to remote device
# Usage: ssh_deploy_frr_config <host> <auth_credential> <auth_type> <frr_config_content> [user]
# Note: Router ID is configured in frr.conf itself (interface lo1 section)
# Returns: 0 if successful, 1 if failed
ssh_deploy_frr_config() {
    local host="$1"
    local auth_credential="$2"
    local auth_type="${3:-key}"
    local frr_config="$4"
    local user="${5:-ubuntu}"

    frr_log_info "Deploying FRR configuration to $host..."

    # Create temporary file with config
    local temp_config=$(mktemp)
    echo "$frr_config" > "$temp_config"

    local ssh_opts="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    local result=0

    # Build the deployment script
    # Note: Router ID on lo1 is configured in frr.conf itself (interface lo1 section)
    # FRR/zebra will apply it automatically on restart/reboot
    local deploy_script="
sudo cp /tmp/frr.conf /etc/frr/frr.conf
sudo chown frr:frr /etc/frr/frr.conf
sudo chmod 640 /etc/frr/frr.conf
sudo systemctl restart frr
sleep 3
echo ''
echo 'Router ID on lo1 (managed by FRR):'
ip addr show lo1 2>/dev/null | grep -E 'inet ' || echo '  (waiting for FRR to apply...)'
echo ''
echo 'BGP Summary:'
sudo vtysh -c 'show bgp summary' | head -20
"

    if [[ "$auth_type" == "key" ]]; then
        # Copy config file
        scp $ssh_opts -i "$auth_credential" "$temp_config" "${user}@${host}:/tmp/frr.conf" 2>/dev/null

        # Apply configuration
        ssh $ssh_opts -i "$auth_credential" "${user}@${host}" "$deploy_script" 2>&1
        result=$?
    else
        # Password auth (requires sshpass)
        sshpass -p "$auth_credential" scp $ssh_opts "$temp_config" "${user}@${host}:/tmp/frr.conf" 2>/dev/null

        sshpass -p "$auth_credential" ssh $ssh_opts "${user}@${host}" "$deploy_script" 2>&1
        result=$?
    fi

    rm -f "$temp_config"

    if [[ $result -eq 0 ]]; then
        frr_log_success "FRR configuration deployed to $host"
    else
        frr_log_error "Failed to deploy FRR configuration to $host"
    fi

    return $result
}

# Deploy FRR daemons configuration to remote device
# Usage: ssh_deploy_frr_daemons <host> <auth_credential> <auth_type> [user]
ssh_deploy_frr_daemons() {
    local host="$1"
    local auth_credential="$2"
    local auth_type="${3:-key}"
    local user="${4:-ubuntu}"

    frr_log_info "Deploying FRR daemons configuration to $host..."

    local daemons_config=$(generate_frr_daemons_config)
    local temp_config=$(mktemp)
    echo "$daemons_config" > "$temp_config"

    local ssh_opts="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    local result=0

    if [[ "$auth_type" == "key" ]]; then
        scp $ssh_opts -i "$auth_credential" "$temp_config" "${user}@${host}:/tmp/daemons" 2>/dev/null
        ssh $ssh_opts -i "$auth_credential" "${user}@${host}" "sudo cp /tmp/daemons /etc/frr/daemons && sudo chown frr:frr /etc/frr/daemons" 2>/dev/null
        result=$?
    else
        sshpass -p "$auth_credential" scp $ssh_opts "$temp_config" "${user}@${host}:/tmp/daemons" 2>/dev/null
        sshpass -p "$auth_credential" ssh $ssh_opts "${user}@${host}" "sudo cp /tmp/daemons /etc/frr/daemons && sudo chown frr:frr /etc/frr/daemons" 2>/dev/null
        result=$?
    fi

    rm -f "$temp_config"
    return $result
}

# Verify FRR status on remote device
# Usage: ssh_verify_frr_status <host> <auth_credential> <auth_type> [user]
# Output: BGP summary
ssh_verify_frr_status() {
    local host="$1"
    local auth_credential="$2"
    local auth_type="${3:-key}"
    local user="${4:-ubuntu}"

    frr_log_info "Verifying FRR status on $host..."

    local ssh_opts="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

    if [[ "$auth_type" == "key" ]]; then
        ssh $ssh_opts -i "$auth_credential" "${user}@${host}" "sudo vtysh -c 'show bgp summary'" 2>/dev/null
    else
        sshpass -p "$auth_credential" ssh $ssh_opts "${user}@${host}" "sudo vtysh -c 'show bgp summary'" 2>/dev/null
    fi
}

################################################################################
# Validation Functions
################################################################################

# Validate device configuration has required fields
# Usage: validate_frr_device_config <config_file> <device_index>
# Returns: 0 if valid, 1 if invalid
validate_frr_device_config() {
    local config_file="$1"
    local device_index="$2"
    local errors=0

    local name=$(yq eval ".frr_config.devices[$device_index].name" "$config_file")
    local host=$(yq eval ".frr_config.devices[$device_index].host" "$config_file")
    local router_id=$(yq eval ".frr_config.devices[$device_index].router_id" "$config_file")
    local asn=$(yq eval ".frr_config.devices[$device_index].asn" "$config_file")

    if [[ -z "$name" || "$name" == "null" ]]; then
        frr_log_error "Device $device_index: missing 'name'"
        errors=$((errors + 1))
    fi

    if [[ -z "$host" || "$host" == "null" ]]; then
        frr_log_error "Device $device_index: missing 'host'"
        errors=$((errors + 1))
    fi

    if [[ -z "$router_id" || "$router_id" == "null" ]]; then
        frr_log_error "Device $device_index: missing 'router_id'"
        errors=$((errors + 1))
    fi

    if [[ -z "$asn" || "$asn" == "null" ]]; then
        frr_log_error "Device $device_index: missing 'asn'"
        errors=$((errors + 1))
    fi

    if [[ $errors -gt 0 ]]; then
        return 1
    fi

    return 0
}

# Validate VDC configuration file
# Usage: validate_vdc_config <vdc_config_file>
# Returns: 0 if valid, 1 if invalid
validate_vdc_config() {
    local vdc_config="$1"

    if [[ ! -f "$vdc_config" ]]; then
        frr_log_error "VDC config file not found: $vdc_config"
        return 1
    fi

    local dc_name=$(yq eval '.global.datacenter_name' "$vdc_config" 2>/dev/null)
    if [[ -z "$dc_name" || "$dc_name" == "null" ]]; then
        frr_log_error "VDC config missing 'global.datacenter_name'"
        return 1
    fi

    return 0
}
