#!/bin/bash

###############################################################################
# BGP Configuration Script
# 
# Configures FRR BGP routing for Mellanox interfaces
# This script is embedded in cloud-init user-data and executed on first boot
###############################################################################

set -e

CONFIG_DIR="/etc/frr-bgp-config"
FRR_CONF="/etc/frr/frr.conf"
DAEMONS_CONF="/etc/frr/daemons"
LOG_FILE="/var/log/bgp-configure.log"

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

log "Starting BGP configuration..."

# Check if Mellanox interfaces were detected
if [[ ! -f "${CONFIG_DIR}/mellanox-interfaces.conf" ]]; then
    log "ERROR: Mellanox interfaces file not found"
    log "Run detect-mellanox.sh first"
    exit 1
fi

# Read configuration files
if [[ ! -f "${CONFIG_DIR}/local-asn" ]] || [[ ! -f "${CONFIG_DIR}/router-id" ]]; then
    log "ERROR: Missing BGP configuration files"
    exit 1
fi

LOCAL_ASN=$(cat "${CONFIG_DIR}/local-asn")
ROUTER_ID=$(cat "${CONFIG_DIR}/router-id")

log "Configuration:"
log "  Local ASN: $LOCAL_ASN"
log "  Router ID: $ROUTER_ID"

# Read Mellanox interfaces
mapfile -t MELLANOX_IFACES < "${CONFIG_DIR}/mellanox-interfaces.conf"
IFACE_COUNT=${#MELLANOX_IFACES[@]}

if [[ $IFACE_COUNT -eq 0 ]]; then
    log "WARNING: No Mellanox interfaces found"
    log "Skipping BGP configuration"
    exit 0
fi

log "Mellanox interfaces: ${MELLANOX_IFACES[*]}"

# Enable BGP daemon in FRR
log "Enabling BGP daemon in FRR..."
if [[ -f "$DAEMONS_CONF" ]]; then
    sed -i 's/^bgpd=no/bgpd=yes/' "$DAEMONS_CONF"
else
    log "ERROR: FRR daemons config not found at $DAEMONS_CONF"
    exit 1
fi

# Create FRR configuration
log "Creating FRR BGP configuration..."

cat > "$FRR_CONF" << FRR_EOF
!
! FRR Configuration
! Auto-generated by BGP configuration script
!
frr version 8.1
frr defaults traditional
hostname $(hostname)
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
! BGP Configuration
!
router bgp ${LOCAL_ASN}
 bgp router-id ${ROUTER_ID}
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
FRR_EOF

# Read and configure BGP peers (if exists)
if [[ -f "${CONFIG_DIR}/bgp-peers.conf" ]]; then
    log "Configuring BGP peers..."
    
    PEER_INDEX=0
    while IFS=',' read -r remote_asn remote_ip local_ip; do
        # Skip empty lines and comments
        [[ -z "$remote_asn" ]] && continue
        [[ "$remote_asn" =~ ^# ]] && continue
        
        # Check if we have enough interfaces
        if [[ $PEER_INDEX -ge $IFACE_COUNT ]]; then
            log "WARNING: More peers than Mellanox interfaces, skipping peer: $remote_asn,$remote_ip,$local_ip"
            continue
        fi
        
        IFACE="${MELLANOX_IFACES[$PEER_INDEX]}"
        
        log "  Peer $((PEER_INDEX + 1)): Interface=$IFACE, Remote ASN=$remote_asn, Remote IP=$remote_ip, Local IP=$local_ip"
        
        # Configure interface IP
        log "    Configuring IP $local_ip on interface $IFACE"
        ip addr flush dev "$IFACE" 2>/dev/null || true
        ip addr add "$local_ip/30" dev "$IFACE" 2>/dev/null || true
        ip link set "$IFACE" up
        
        # Add BGP neighbor configuration
        cat >> "$FRR_CONF" << FRR_EOF
 !
 neighbor ${remote_ip} remote-as ${remote_asn}
 neighbor ${remote_ip} description Peer on ${IFACE}
FRR_EOF
        
        ((PEER_INDEX++))
    done < "${CONFIG_DIR}/bgp-peers.conf"
    
    log "Configured $PEER_INDEX BGP peer(s)"
else
    log "No BGP peers configuration found"
fi

# Configure address family
cat >> "$FRR_CONF" << 'FRR_EOF'
 !
 address-family ipv4 unicast
FRR_EOF

# Activate neighbors
if [[ -f "${CONFIG_DIR}/bgp-peers.conf" ]]; then
    PEER_INDEX=0
    while IFS=',' read -r remote_asn remote_ip local_ip; do
        [[ -z "$remote_asn" ]] && continue
        [[ "$remote_asn" =~ ^# ]] && continue
        [[ $PEER_INDEX -ge $IFACE_COUNT ]] && continue
        
        cat >> "$FRR_CONF" << FRR_EOF
  neighbor ${remote_ip} activate
FRR_EOF
        
        ((PEER_INDEX++))
    done < "${CONFIG_DIR}/bgp-peers.conf"
fi

# Add network advertisements (if configured)
if [[ -f "${CONFIG_DIR}/bgp-networks" ]]; then
    BGP_NETWORKS=$(cat "${CONFIG_DIR}/bgp-networks")
    if [[ -n "$BGP_NETWORKS" ]]; then
        log "Configuring network advertisements..."
        
        IFS=',' read -ra NETWORKS <<< "$BGP_NETWORKS"
        for network in "${NETWORKS[@]}"; do
            # Trim whitespace
            network=$(echo "$network" | xargs)
            if [[ -n "$network" ]]; then
                log "  Advertising network: $network"
                cat >> "$FRR_CONF" << FRR_EOF
  network ${network}
FRR_EOF
            fi
        done
    fi
else
    log "No BGP networks to advertise"
fi

# Close address-family and router bgp
cat >> "$FRR_CONF" << 'FRR_EOF'
 exit-address-family
!
line vty
!
FRR_EOF

log "FRR configuration written to: $FRR_CONF"

# Set proper permissions
chown frr:frr "$FRR_CONF"
chmod 640 "$FRR_CONF"

log "BGP configuration complete"
log "FRR service will be started by cloud-init"
