#!/bin/bash

###############################################################################
# BGP Configuration Module
# Configures FRR BGP for Mellanox interfaces
###############################################################################

configure_bgp() {
    local work_dir="$1"
    local local_asn="$2"
    local router_id="$3"
    local bgp_config_file="$4"
    local bgp_networks="$5"
    
    local squashfs_extract="${work_dir}/squashfs_extract"
    local template_dir="${SCRIPT_DIR}/templates"
    
    # Create BGP configuration directory
    mkdir -p "${squashfs_extract}/etc/frr-bgp-config"
    
    # Copy BGP peers configuration if provided
    if [[ -n "$bgp_config_file" ]] && [[ -f "$bgp_config_file" ]]; then
        echo "  - Copying BGP peers configuration..."
        cp "$bgp_config_file" "${squashfs_extract}/etc/frr-bgp-config/bgp-peers.conf"
    fi
    
    # Save local ASN, router ID, and networks
    echo "$local_asn" > "${squashfs_extract}/etc/frr-bgp-config/local-asn"
    echo "$router_id" > "${squashfs_extract}/etc/frr-bgp-config/router-id"
    
    # Save BGP networks to advertise if provided
    if [[ -n "$bgp_networks" ]]; then
        echo "  - Saving BGP networks to advertise..."
        echo "$bgp_networks" > "${squashfs_extract}/etc/frr-bgp-config/bgp-networks"
    fi
    
    # Create BGP configuration script
    echo "  - Creating BGP configuration script..."
    
    cat > "${squashfs_extract}/usr/local/bin/configure-bgp.sh" << 'BGPEOF'
#!/bin/bash

###############################################################################
# BGP Configuration Script
# Configures FRR BGP for Mellanox interfaces on first boot
###############################################################################

MELLANOX_IFACES_FILE="/etc/mellanox-interfaces.conf"
BGP_PEERS_FILE="/etc/frr-bgp-config/bgp-peers.conf"
LOCAL_ASN_FILE="/etc/frr-bgp-config/local-asn"
ROUTER_ID_FILE="/etc/frr-bgp-config/router-id"
BGP_NETWORKS_FILE="/etc/frr-bgp-config/bgp-networks"
FRR_CONF="/etc/frr/frr.conf"

configure_bgp() {
    # Read local ASN
    if [[ ! -f "$LOCAL_ASN_FILE" ]]; then
        echo "ERROR: Local ASN file not found"
        return 1
    fi
    
    local local_asn=$(cat "$LOCAL_ASN_FILE")
    
    # Read router ID
    if [[ ! -f "$ROUTER_ID_FILE" ]]; then
        echo "ERROR: Router ID file not found"
        return 1
    fi
    
    local router_id=$(cat "$ROUTER_ID_FILE")
    
    # Read Mellanox interfaces
    local mellanox_ifaces=()
    if [[ -f "$MELLANOX_IFACES_FILE" ]]; then
        while IFS= read -r iface; do
            [[ -n "$iface" ]] && mellanox_ifaces+=("$iface")
        done < "$MELLANOX_IFACES_FILE"
    fi
    
    # Read BGP networks to advertise if configured
    local bgp_networks=""
    if [[ -f "$BGP_NETWORKS_FILE" ]]; then
        bgp_networks=$(cat "$BGP_NETWORKS_FILE")
    fi
    
    echo "Configuring BGP with local ASN: $local_asn"
    echo "Router ID: $router_id"
    echo "Mellanox interfaces: ${mellanox_ifaces[*]}"
    if [[ -n "$bgp_networks" ]]; then
        echo "Networks to advertise: $bgp_networks"
    else
        echo "WARNING: No networks configured for advertisement"
    fi
    
    # Start FRR configuration
    cat > "$FRR_CONF" << EOF
! FRR Configuration
! Generated by os-repacker
frr version 8.1
frr defaults traditional
hostname $(hostname)
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
! BGP Configuration
router bgp $local_asn
 bgp router-id $router_id
 bgp log-neighbor-changes
 no bgp default ipv4-unicast
 !
 neighbor MELLANOX peer-group
 neighbor MELLANOX timers 3 10
 neighbor MELLANOX timers connect 10
 !
 address-family ipv4 unicast
  neighbor MELLANOX activate
  neighbor MELLANOX soft-reconfiguration inbound
  neighbor MELLANOX route-map ALLOW-ALL in
  neighbor MELLANOX route-map ALLOW-ALL out
 exit-address-family
!
EOF
    
    # Configure BGP peers if configuration file exists
    if [[ -f "$BGP_PEERS_FILE" ]]; then
        echo "Configuring BGP peers..."
        
        local peer_index=0
        while IFS=',' read -r remote_asn remote_ip local_ip; do
            # Skip comments and empty lines
            [[ "$remote_asn" =~ ^#.*$ ]] && continue
            [[ -z "$remote_asn" ]] && continue
            
            # Trim whitespace
            remote_asn=$(echo "$remote_asn" | xargs)
            remote_ip=$(echo "$remote_ip" | xargs)
            local_ip=$(echo "$local_ip" | xargs)
            
            # Check if we have a Mellanox interface available
            if [[ $peer_index -lt ${#mellanox_ifaces[@]} ]]; then
                local iface="${mellanox_ifaces[$peer_index]}"
                echo "  Configuring BGP peer on $iface: $remote_ip (AS $remote_asn)"
                
                # Configure interface IP
                ip addr add "$local_ip/30" dev "$iface" 2>/dev/null || true
                ip link set "$iface" up
                
                # Add to FRR configuration
                cat >> "$FRR_CONF" << EOF
! Peer on $iface
router bgp $local_asn
 neighbor $remote_ip remote-as $remote_asn
 neighbor $remote_ip peer-group MELLANOX
 neighbor $remote_ip description "BGP peer on $iface"
 neighbor $remote_ip update-source $local_ip
!
EOF
                ((peer_index++))
            else
                echo "  WARNING: More BGP peers than available Mellanox interfaces (skipping)"
                break
            fi
        done < "$BGP_PEERS_FILE"
        
        if [[ $peer_index -eq 0 ]]; then
            echo "  WARNING: No BGP peers configured (no valid entries or no Mellanox interfaces)"
        fi
    fi
    
    # Configure networks to advertise
    if [[ -n "$bgp_networks" ]]; then
        echo "Configuring networks to advertise..."
        
        # Convert comma-separated to array
        IFS=',' read -ra NETWORKS <<< "$bgp_networks"
        
        for network in "${NETWORKS[@]}"; do
            # Trim whitespace
            network=$(echo "$network" | xargs)
            
            if [[ -n "$network" ]]; then
                echo "  Advertising network: $network"
                
                cat >> "$FRR_CONF" << EOF
! Advertise network
router bgp $local_asn
 address-family ipv4 unicast
  network $network
 exit-address-family
!
EOF
            fi
        done
    else
        echo "No networks configured for BGP advertisement"
    fi
    
    # Add route-map
    cat >> "$FRR_CONF" << 'EOF'
! Route maps
route-map ALLOW-ALL permit 10
!
line vty
!
EOF
    
    # Set proper permissions
    chown frr:frr "$FRR_CONF"
    chmod 640 "$FRR_CONF"
    
    # Restart FRR
    echo "Restarting FRR service..."
    systemctl restart frr
    
    echo "BGP configuration completed"
    return 0
}

# Main execution
configure_bgp
BGPEOF
    
    chmod +x "${squashfs_extract}/usr/local/bin/configure-bgp.sh"
    
    # Create systemd service for BGP configuration
    echo "  - Creating systemd service for BGP configuration..."
    
    cat > "${squashfs_extract}/etc/systemd/system/bgp-configure.service" << 'EOF'
[Unit]
Description=Configure BGP on Mellanox Interfaces
After=network-online.target mellanox-detect.service frr.service
Wants=network-online.target
Requires=mellanox-detect.service frr.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/configure-bgp.sh
RemainAfterExit=yes
StandardOutput=journal
StandardError=journal
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
    
    # Enable the service
    chroot "$squashfs_extract" /bin/bash -c "systemctl enable bgp-configure.service" 2>/dev/null || true
    
    echo "  - BGP configuration prepared"
    return 0
}
