#!/bin/bash

###############################################################################
# Cloud-Init User-Data Generator
# 
# Generates cloud-init user-data YAML with embedded BGP configuration scripts
###############################################################################

generate_cloud_init_userdata() {
    local local_asn="$1"
    local router_id="$2"
    local bgp_peers_file="$3"
    local bgp_networks="$4"
    local output_file="$5"
    
    # Read BGP peers content (if provided)
    local bgp_peers_content=""
    if [[ -n "$bgp_peers_file" ]] && [[ -f "$bgp_peers_file" ]]; then
        bgp_peers_content=$(cat "$bgp_peers_file")
    fi
    
    # Read Mellanox detection script
    local detect_script=$(cat "${SCRIPT_DIR}/modules/mellanox-detect-script.sh")
    
    # Read BGP configuration script
    local bgp_config_script=$(cat "${SCRIPT_DIR}/modules/bgp-config-script.sh")
    
    # Indent content for YAML (4 spaces)
    local indent_peers=$(echo "$bgp_peers_content" | sed 's/^/      /')
    local indent_detect=$(echo "$detect_script" | sed 's/^/      /')
    local indent_bgp=$(echo "$bgp_config_script" | sed 's/^/      /')
    
    # Generate cloud-init user-data
    cat > "$output_file" << 'USERDATA_EOF'
#cloud-config
# Generated by stage2-network.sh (Cloud-Init Mode)
# 
# This file configures Mellanox interface detection and BGP routing
# using FRR on Ubuntu 24.04
#
USERDATA_EOF
    
    # Add metadata comments
    cat >> "$output_file" << USERDATA_EOF
# Configuration:
#   Local ASN: ${local_asn}
#   Router ID: ${router_id}
$(if [[ -n "$bgp_networks" ]]; then echo "#   BGP Networks: ${bgp_networks}"; fi)
#
# Generated on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

USERDATA_EOF
    
    # Add write_files section
    cat >> "$output_file" << USERDATA_EOF
# Write configuration files and scripts
write_files:
  # === BGP Configuration Files ===
  
  - path: /etc/frr-bgp-config/local-asn
    content: "${local_asn}"
    owner: root:root
    permissions: '0644'
  
  - path: /etc/frr-bgp-config/router-id
    content: "${router_id}"
    owner: root:root
    permissions: '0644'
  
USERDATA_EOF
    
    # Add BGP peers if provided
    if [[ -n "$bgp_peers_content" ]]; then
        cat >> "$output_file" << USERDATA_EOF
  - path: /etc/frr-bgp-config/bgp-peers.conf
    content: |
${indent_peers}
    owner: root:root
    permissions: '0644'
  
USERDATA_EOF
    fi
    
    # Add BGP networks if provided
    if [[ -n "$bgp_networks" ]]; then
        cat >> "$output_file" << USERDATA_EOF
  - path: /etc/frr-bgp-config/bgp-networks
    content: "${bgp_networks}"
    owner: root:root
    permissions: '0644'
  
USERDATA_EOF
    fi
    
    # Add Mellanox detection script
    cat >> "$output_file" << USERDATA_EOF
  # === Mellanox Interface Detection Script ===
  
  - path: /usr/local/bin/detect-mellanox.sh
    owner: root:root
    permissions: '0755'
    content: |
${indent_detect}
  
USERDATA_EOF
    
    # Add BGP configuration script
    cat >> "$output_file" << USERDATA_EOF
  # === BGP Configuration Script ===
  
  - path: /usr/local/bin/configure-bgp.sh
    owner: root:root
    permissions: '0755'
    content: |
${indent_bgp}

USERDATA_EOF
    
    # Add runcmd section
    cat >> "$output_file" << 'USERDATA_EOF'
# Execute configuration on boot
runcmd:
  - echo "=== Starting Network Configuration ==="
  - echo "Detecting Mellanox interfaces..."
  - /usr/local/bin/detect-mellanox.sh 2>&1 | tee -a /var/log/network-setup.log
  - echo "Configuring BGP with FRR..."
  - /usr/local/bin/configure-bgp.sh 2>&1 | tee -a /var/log/network-setup.log
  - echo "Enabling FRR service..."
  - systemctl enable frr
  - systemctl start frr
  - echo "=== Network Configuration Complete ==="
  - echo "Check 'sudo vtysh -c \"show ip bgp summary\"' for BGP status"

# Set timezone
timezone: UTC

# Optional: Package updates (uncomment if needed)
# package_update: true
# package_upgrade: false

USERDATA_EOF
    
    echo "Cloud-init user-data generated: $output_file"
}

generate_cloud_init_metadata() {
    local output_file="$1"
    local instance_id="${2:-bgp-router-$(date +%s)}"
    local hostname="${3:-bgp-router}"
    
    cat > "$output_file" << METADATA_EOF
instance-id: ${instance_id}
local-hostname: ${hostname}
METADATA_EOF
    
    echo "Cloud-init meta-data generated: $output_file"
}
